# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oscill_modif.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(685, 624)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.qwtPlot = QwtPlot(self.centralwidget)
        self.qwtPlot.setAutoReplot(True)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.horizontalLayout_2.addWidget(self.qwtPlot)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.wakeUpButton = QtGui.QPushButton(self.centralwidget)
        self.wakeUpButton.setObjectName(_fromUtf8("wakeUpButton"))
        self.horizontalLayout.addWidget(self.wakeUpButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.durationEdit = QtGui.QLineEdit(self.centralwidget)
        self.durationEdit.setObjectName(_fromUtf8("durationEdit"))
        self.horizontalLayout_4.addWidget(self.durationEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_5.addWidget(self.saveButton)
        self.fileNameEdit = QtGui.QLineEdit(self.centralwidget)
        self.fileNameEdit.setObjectName(_fromUtf8("fileNameEdit"))
        self.horizontalLayout_5.addWidget(self.fileNameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.immediateButton = QtGui.QRadioButton(self.centralwidget)
        self.immediateButton.setChecked(True)
        self.immediateButton.setObjectName(_fromUtf8("immediateButton"))
        self.horizontalLayout_6.addWidget(self.immediateButton)
        self.finalButton = QtGui.QRadioButton(self.centralwidget)
        self.finalButton.setObjectName(_fromUtf8("finalButton"))
        self.horizontalLayout_6.addWidget(self.finalButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.thresholdEdit = QtGui.QLineEdit(self.centralwidget)
        self.thresholdEdit.setObjectName(_fromUtf8("thresholdEdit"))
        self.horizontalLayout_7.addWidget(self.thresholdEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.fitButton = QtGui.QPushButton(self.centralwidget)
        self.fitButton.setObjectName(_fromUtf8("fitButton"))
        self.verticalLayout.addWidget(self.fitButton)
        self.fitEdit = QtGui.QLineEdit(self.centralwidget)
        self.fitEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.fitEdit.setReadOnly(True)
        self.fitEdit.setObjectName(_fromUtf8("fitEdit"))
        self.verticalLayout.addWidget(self.fitEdit)
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.verticalLayout.addWidget(self.closeButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Save_Ctrl_S = QtGui.QAction(MainWindow)
        self.action_Save_Ctrl_S.setObjectName(_fromUtf8("action_Save_Ctrl_S"))
        self.action_Quit_Ctrl_Q = QtGui.QAction(MainWindow)
        self.action_Quit_Ctrl_Q.setObjectName(_fromUtf8("action_Quit_Ctrl_Q"))
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menu_File.addAction(self.action_Save_Ctrl_S)
        self.menu_File.addAction(self.action_Quit_Ctrl_Q)
        self.menu_Help.addAction(self.actionManual)
        self.menu_Help.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.wakeUpButton.setToolTip(_translate("MainWindow", "Prepares the experiment, which will start upon a quick voltage change", None))
        self.wakeUpButton.setText(_translate("MainWindow", "Wake up", None))
        self.stopButton.setToolTip(_translate("MainWindow", "Stopthe record immediately", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.label.setToolTip(_translate("MainWindow", "How long must we gather data?", None))
        self.label.setText(_translate("MainWindow", "Duration (s):", None))
        self.durationEdit.setToolTip(_translate("MainWindow", "How long must we gather data?", None))
        self.durationEdit.setText(_translate("MainWindow", "15", None))
        self.saveButton.setToolTip(_translate("MainWindow", "Where should we store the data?", None))
        self.saveButton.setText(_translate("MainWindow", "Save to:", None))
        self.fileNameEdit.setToolTip(_translate("MainWindow", "Where should we store the data?", None))
        self.fileNameEdit.setText(_translate("MainWindow", "oscill.dat", None))
        self.label_3.setText(_translate("MainWindow", "Plot:", None))
        self.immediateButton.setToolTip(_translate("MainWindow", "The plot is refreshed during the experiment", None))
        self.immediateButton.setText(_translate("MainWindow", "immediate", None))
        self.finalButton.setToolTip(_translate("MainWindow", "The plot appears after the end of the experiment", None))
        self.finalButton.setText(_translate("MainWindow", "finally", None))
        self.label_4.setToolTip(_translate("MainWindow", "voltage variation to trigger the record", None))
        self.label_4.setText(_translate("MainWindow", "Threshold (V/s): ", None))
        self.thresholdEdit.setToolTip(_translate("MainWindow", "voltage variation to trigger the record", None))
        self.thresholdEdit.setText(_translate("MainWindow", "50", None))
        self.fitButton.setToolTip(_translate("MainWindow", "Compare with a mathematic model", None))
        self.fitButton.setText(_translate("MainWindow", "Fit", None))
        self.fitEdit.setToolTip(_translate("MainWindow", "Compare with a mathematic model", None))
        self.closeButton.setText(_translate("MainWindow", "Close", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.action_Save_Ctrl_S.setText(_translate("MainWindow", "&Save (Ctrl+S)", None))
        self.action_Save_Ctrl_S.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_Quit_Ctrl_Q.setText(_translate("MainWindow", "&Quit (Ctrl+Q)", None))
        self.action_Quit_Ctrl_Q.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionManual.setText(_translate("MainWindow", "Manual", None))
        self.actionManual.setShortcut(_translate("MainWindow", "F1", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))

from qwt import QwtPlot
